import pandas as pd
from datetime import datetime, timedelta
from typing import Optional, Callable, Union
from functools import wraps
import json
import os
from src.utils import setup_logger

logger = setup_logger(__name__)


def save_to_file(filename: Optional[str] = None):
    """Декоратор для сохранения результата функции в JSON-файл.
    Если filename не передан — имя будет autogenerated."""

    def decorator(func: Callable):
        @wraps(func)
        def wrapper(*args, **kwargs):
            result = func(*args, **kwargs)

            out_file = filename
            if not out_file:
                now = datetime.now().strftime("%Y%m%d_%H%M%S")
                out_file = f"report_{now}.json"

            with open(out_file, "w", encoding="utf-8") as f:
                json.dump(result, f, ensure_ascii=False, indent=2)

            return result

        return wrapper

    return decorator


@save_to_file()  # Используем без параметра — файл назовётся автоматически
def spending_by_workday(transactions: pd.DataFrame, date: Optional[str] = None) -> dict:
    """Возвращает средние расходы по рабочим и выходным дням за последние 3 месяца от даты.

    Args:
        transactions (pd.DataFrame): таблица с транзакциями
        date (Optional[str]): дата в формате 'YYYY-MM-DD'

    Returns:
        dict: средние расходы {'Будни': ..., 'Выходные': ...}
    """
    if date:
        end = pd.to_datetime(date)
    else:
        end = pd.to_datetime(datetime.today().date())

    start = end - pd.DateOffset(months=3)

    df = transactions.copy()
    df["Дата операции"] = pd.to_datetime(df["Дата операции"], errors="coerce")
    df = df[(df["Дата операции"] >= start) & (df["Дата операция"] <= end)]
    df = df[df["Сумма операции"] < 0]  # Только расходы

    df["weekday"] = df["Дата операции"].dt.weekday
    df["is_weekend"] = df["weekday"] >= 5

    workday_avg = abs(df[~df["is_weekend"]]["Сумма операции"].mean())
    weekend_avg = abs(df[df["is_weekend"]]["Сумма операции"].mean())

    return {"Будни": round(workday_avg or 0), "Выходные": round(weekend_avg or 0)}
